packages:
  - packages/*
  - playground/*
  - docs
catalog:
  '@antfu/eslint-config': ^3.8.0
  '@commitlint/cli': ^19.5.0
  '@commitlint/config-conventional': ^19.5.0
  '@dcloudio/types': ^3.4.14
  '@dcloudio/uni-app': 3.0.0-alpha-4030220241101001
  '@dcloudio/uni-app-plus': 3.0.0-alpha-4030220241101001
  '@dcloudio/uni-h5': 3.0.0-alpha-4030220241101001
  '@dcloudio/uni-mp-weixin': 3.0.0-alpha-4030220241101001
  '@dcloudio/uni-ui': ^1.5.7
  '@dcloudio/vite-plugin-uni': 3.0.0-alpha-4030220241101001
  '@iconify/vue': ^4.1.2
  '@types/fs-extra': ^11.0.4
  '@uni-helper/uni-app-types': ^1.0.0-alpha.5
  '@uni-helper/uni-ui-types': ^1.0.0-alpha.5
  '@uni-helper/uni-use': ^0.19.14
  '@uni-helper/unocss-preset-uni': ^0.2.10
  '@uni-helper/vite-plugin-uni-components': ^0.1.0
  '@uni-helper/vite-plugin-uni-layouts': ^0.1.10
  '@uni-helper/vite-plugin-uni-pages': ^0.2.28
  '@unocss/eslint-plugin': ^0.63.6
  '@unocss/reset': ^0.63.6
  '@vitejs/plugin-vue': ^5.1.4
  '@vitejs/plugin-vue-jsx': ^4.0.1
  '@vue/tsconfig': ^0.5.1
  '@vueuse/core': ^11.2.0
  bumpp: ^9.8.0
  c12: ^2.0.1
  cac: ^6.7.14
  conventional-changelog-cli: ^5.0.0
  defu: ^6.1.4
  eslint: ^9.14.0
  eslint-plugin-format: ^0.1.2
  find-up: ^7.0.0
  fs-extra: ^11.2.0
  lint-staged: ^15.2.10
  mlly: ^1.7.2
  pathe: ^1.1.2
  pinia: ^2.2.6
  pinia-plugin-persistedstate: ^4.1.2
  pkg-types: ^1.2.1
  sass: ^1.80.6
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  tsx: ^4.19.2
  typescript: ^5.6.3
  unbuild: ^2.0.0
  unocss: ^0.63.6
  unplugin-auto-import: ^0.18.3
  unplugin-vue-components: ^0.27.4
  unplugin-vue-router: ^0.10.8
  uview-plus: ^3.3.38
  vite: ^5.4.10
  vite-plugin-checker: ^0.8.0
  vite-plugin-vue-devtools: ^7.6.2
  vite-plugin-vue-layouts: ^0.11.0
  vitepress: ^1.4.5
  vue: ^3.5.12
  vue-router: ^4.4.5
  vue-tsc: 2.1.10
