packages:
  - packages/*
  - playground/*
catalog:
  '@antfu/eslint-config': ^3.2.0
  '@commitlint/cli': ^19.4.1
  '@commitlint/config-conventional': ^19.4.1
  '@dcloudio/types': ^3.4.12
  '@dcloudio/uni-app': 3.0.0-alpha-4020720240904001
  '@dcloudio/uni-app-plus': 3.0.0-alpha-4020720240904001
  '@dcloudio/uni-h5': 3.0.0-alpha-4020720240904001
  '@dcloudio/uni-mp-weixin': 3.0.0-alpha-4020720240904001
  '@dcloudio/uni-ui': ^1.5.6
  '@dcloudio/vite-plugin-uni': 3.0.0-alpha-4020720240904001
  '@iconify/vue': ^4.1.2
  '@types/fs-extra': ^11.0.4
  '@uni-helper/uni-app-types': ^0.5.13
  '@uni-helper/uni-ui-types': ^0.5.15
  '@uni-helper/uni-use': ^0.19.14
  '@uni-helper/unocss-preset-uni': ^0.2.9
  '@uni-helper/vite-plugin-uni-components': ^0.1.0
  '@uni-helper/vite-plugin-uni-layouts': ^0.1.10
  '@uni-helper/vite-plugin-uni-pages': 0.2.24
  '@unocss/eslint-plugin': 0.61.6
  '@unocss/reset': ^0.61.6
  '@vitejs/plugin-vue': ^5.1.3
  '@vitejs/plugin-vue-jsx': ^4.0.1
  '@vue/tsconfig': ^0.5.1
  '@vueuse/core': ^11.0.3
  bumpp: ^9.5.2
  c12: ^1.11.2
  cac: ^6.7.14
  conventional-changelog-cli: ^5.0.0
  defu: ^6.1.4
  eslint: ^9.9.1
  eslint-plugin-format: ^0.1.2
  find-up: ^7.0.0
  fs-extra: ^11.2.0
  lint-staged: ^15.2.10
  mlly: 1.7.1
  pathe: ^1.1.2
  pinia: ^2.2.2
  pkg-types: ^1.2.0
  sass: 1.78.0
  simple-git-hooks: ^2.11.1
  taze: ^0.16.7
  tsx: ^4.19.0
  typescript: ^5.5.4
  unbuild: ^2.0.0
  unocss: 0.61.6
  unplugin-auto-import: ^0.18.2
  unplugin-vue-components: ^0.27.4
  unplugin-vue-router: ^0.10.7
  uview-plus: ^3.3.31
  vite: ^5.4.3
  vite-plugin-checker: ^0.7.2
  vite-plugin-vue-devtools: ^7.4.4
  vite-plugin-vue-layouts: ^0.11.0
  vitepress: ^1.3.4
  vue: ^3.5.1
  vue-router: ^4.4.3
  vue-tsc: 2.0.26
